"use client";

import {
  Activity,
  AppWindow,
  Archive,
  BadgeCheck,
  Banknote,
  Barcode,
  Bell,
  BookOpen,
  Bookmark,
  Boxes,
  Building,
  Building2,
  Calculator,
  Calendar,
  Camera,
  ChartColumn,
  ChartLine,
  ChartPie,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  Cpu,
  Database,
  Eye,
  Factory,
  FileCheck,
  FileSearch,
  FileText,
  Filter,
  Flag,
  FlaskConical,
  Folder,
  FolderOpen,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  HardDrive,
  Image,
  Inbox,
  Info,
  Key,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  Mail,
  MapPin,
  Microscope,
  Monitor,
  Network,
  NotebookPen,
  Package,
  Percent,
  Phone,
  Plug,
  Presentation,
  Printer,
  QrCode,
  Receipt,
  Recycle,
  Ruler,
  Scale,
  Scan,
  Send,
  Server,
  Settings,
  Sheet,
  ShieldCheck,
  ShoppingCart,
  SquareCheck,
  Star,
  StickyNote,
  Table,
  Tag,
  Target,
  Thermometer,
  TrendingUp,
  TriangleAlert,
  Truck,
  UserCheck,
  Users,
  Warehouse,
  Wifi,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/**
 * Catálogo de ícones oferecidos ao admin.
 *
 * O Lucide traz mais de 2000 ícones; aqui há 92, escolhidos para o que o
 * portal reúne (sistemas, qualidade, produção). Um seletor com dois mil
 * ícones não ajuda ninguém a decidir, e imports estáticos de um conjunto
 * fechado evitam 92 carregamentos preguiçosos ao abrir o seletor.
 *
 * Os nomes estão em kebab-case, que é o formato aceito pelo Apps Script
 * (ver normalizeIcon_ em Code.gs) e o que resolveAppIcon() usa na leitura.
 * Gerado com validação contra os exports reais do lucide-react.
 */

export type IconGroup = {
  id: string;
  label: { pt: string; en: string };
  icons: string[];
};

export const ICON_CATALOG: Record<string, LucideIcon> = {
  "app-window": AppWindow,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "monitor": Monitor,
  "server": Server,
  "database": Database,
  "network": Network,
  "cpu": Cpu,
  "hard-drive": HardDrive,
  "cloud": Cloud,
  "globe": Globe,
  "link": Link,
  "wifi": Wifi,
  "shield-check": ShieldCheck,
  "badge-check": BadgeCheck,
  "circle-check": CircleCheck,
  "square-check": SquareCheck,
  "list-checks": ListChecks,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "file-check": FileCheck,
  "file-search": FileSearch,
  "microscope": Microscope,
  "flask-conical": FlaskConical,
  "thermometer": Thermometer,
  "ruler": Ruler,
  "scale": Scale,
  "target": Target,
  "triangle-alert": TriangleAlert,
  "eye": Eye,
  "scan": Scan,
  "qr-code": QrCode,
  "barcode": Barcode,
  "chart-column": ChartColumn,
  "chart-pie": ChartPie,
  "chart-line": ChartLine,
  "trending-up": TrendingUp,
  "table": Table,
  "sheet": Sheet,
  "presentation": Presentation,
  "calculator": Calculator,
  "percent": Percent,
  "gauge": Gauge,
  "activity": Activity,
  "filter": Filter,
  "file-text": FileText,
  "folder": Folder,
  "folder-open": FolderOpen,
  "archive": Archive,
  "book-open": BookOpen,
  "notebook-pen": NotebookPen,
  "sticky-note": StickyNote,
  "printer": Printer,
  "inbox": Inbox,
  "send": Send,
  "mail": Mail,
  "factory": Factory,
  "package": Package,
  "boxes": Boxes,
  "truck": Truck,
  "warehouse": Warehouse,
  "wrench": Wrench,
  "settings": Settings,
  "workflow": Workflow,
  "git-branch": GitBranch,
  "recycle": Recycle,
  "leaf": Leaf,
  "zap": Zap,
  "lightbulb": Lightbulb,
  "plug": Plug,
  "users": Users,
  "user-check": UserCheck,
  "building": Building,
  "building-2": Building2,
  "calendar": Calendar,
  "clock": Clock,
  "phone": Phone,
  "shopping-cart": ShoppingCart,
  "receipt": Receipt,
  "banknote": Banknote,
  "graduation-cap": GraduationCap,
  "tag": Tag,
  "bookmark": Bookmark,
  "star": Star,
  "flag": Flag,
  "map-pin": MapPin,
  "key": Key,
  "lock": Lock,
  "bell": Bell,
  "image": Image,
  "camera": Camera,
  "info": Info,
};

export const ICON_GROUPS: IconGroup[] = [
  {
    id: "sistemas",
    label: { pt: "Sistemas", en: "Systems" },
    icons: ["app-window", "layout-dashboard", "layout-grid", "monitor", "server", "database", "network", "cpu", "hard-drive", "cloud", "globe", "link", "wifi"],
  },
  {
    id: "qualidade",
    label: { pt: "Qualidade", en: "Quality" },
    icons: ["shield-check", "badge-check", "circle-check", "square-check", "list-checks", "clipboard-check", "clipboard-list", "file-check", "file-search", "microscope", "flask-conical", "thermometer", "ruler", "scale", "target", "triangle-alert", "eye", "scan", "qr-code", "barcode"],
  },
  {
    id: "dados",
    label: { pt: "Dados", en: "Data" },
    icons: ["chart-column", "chart-pie", "chart-line", "trending-up", "table", "sheet", "presentation", "calculator", "percent", "gauge", "activity", "filter"],
  },
  {
    id: "documentos",
    label: { pt: "Documentos", en: "Documents" },
    icons: ["file-text", "folder", "folder-open", "archive", "book-open", "notebook-pen", "sticky-note", "printer", "inbox", "send", "mail"],
  },
  {
    id: "producao",
    label: { pt: "Produção", en: "Production" },
    icons: ["factory", "package", "boxes", "truck", "warehouse", "wrench", "settings", "workflow", "git-branch", "recycle", "leaf", "zap", "lightbulb", "plug"],
  },
  {
    id: "pessoas",
    label: { pt: "Pessoas", en: "People" },
    icons: ["users", "user-check", "building", "building-2", "calendar", "clock", "phone", "shopping-cart", "receipt", "banknote", "graduation-cap"],
  },
  {
    id: "marcadores",
    label: { pt: "Marcadores", en: "Markers" },
    icons: ["tag", "bookmark", "star", "flag", "map-pin", "key", "lock", "bell", "image", "camera", "info"],
  },
];

export const DEFAULT_ICON = "app-window";

export function isKnownIcon(name: string): boolean {
  return name in ICON_CATALOG;
}
